import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'

import { Header } from "@/components/Header";
import { Footer } from "@/components/FooterSection";
import { Toaster } from "@/components/ui/toaster"
import SessionProviderWrapper from "@/components/SessionProviderWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={inter.className}>
      <SessionProviderWrapper>
        <Header/>
        {children}
        <Footer/>
        <Toaster />
        </SessionProviderWrapper>
      </body>
    </html>
  );
}

